# Generated by Django 3.2.8 on 2021-10-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="creator",
            new_name="user",
        ),
    ]
